# 2. Pandas Crash - Basic Pandas

## Pandas 는 Series data type 과 DataFrame data type 으로 구성된다.

### Series (1 차원) : numpy array 와 유사. 
- 차이점 - numpy 와 달리 Series 는 axis (행, 열)에 label 을 부여할 수 있다. 즉, numpy 와 같이 숫자로만 indexing 하는 것이 아니라 label 명으로 indexing 을 할 수 있다. 또한 숫자 뿐 아니라 임의의 Python object 를 모두 element 로 가질 수 있다.

### DataFrame (2차원, table)
- Python program 안의 Excel

### Series vs DataFrame
<img src="https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png" width="500">

<img src="https://ichi.pro/assets/images/max/724/1*CuHNQWNiCnwIpGKZQO91bg.png" width="600">

In [3]:
import numpy as np
import pandas as pd

### DataFrame 

DataFrame 은 여러개의 Series 를 같은 index 기준으로 모아 Table 을 만든 것이다.

In [4]:
np.random.seed(101)
data = np.random.randn(5, 4)

In [5]:
df = pd.DataFrame(data, columns=['W', 'X', 'Y', 'Z'])
df

          W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

### dataframe 의 column 명

In [6]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 288.0 bytes

In [8]:
df.describe()

              W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

### DataFrame indexing

In [9]:
df['W']

0    2.706850
1    0.651118
2   -2.018168
3    0.188695
4    0.190794
Name: W, dtype: float64

In [10]:
type(df['W'])

pandas.core.series.Series

In [11]:
df[['W', 'Z']]

          W         Z
0  2.706850  0.503826
1  0.651118  0.605965
2 -2.018168 -0.589001
3  0.188695  0.955057
4  0.190794  0.683509

In [12]:
df.W

0    2.706850
1    0.651118
2   -2.018168
3    0.188695
4    0.190794
Name: W, dtype: float64

### new column 추가/삭제

In [13]:
df['new'] = df['W'] + df['X']
df

          W         X         Y         Z       new
0  2.706850  0.628133  0.907969  0.503826  3.334983
1  0.651118 -0.319318 -0.848077  0.605965  0.331800
2 -2.018168  0.740122  0.528813 -0.589001 -1.278046
3  0.188695 -0.758872 -0.933237  0.955057 -0.570177
4  0.190794  1.978757  2.605967  0.683509  2.169552

In [14]:
df.drop('new', axis=1)

          W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [15]:
df

          W         X         Y         Z       new
0  2.706850  0.628133  0.907969  0.503826  3.334983
1  0.651118 -0.319318 -0.848077  0.605965  0.331800
2 -2.018168  0.740122  0.528813 -0.589001 -1.278046
3  0.188695 -0.758872 -0.933237  0.955057 -0.570177
4  0.190794  1.978757  2.605967  0.683509  2.169552

In [16]:
df.drop('new', axis=1, inplace=True)
df

          W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [17]:
df.shape

(5, 4)

### Missing Data 처리

- missing data 가 있는 row 혹은 columns 을 완전히 삭제 : dropna()
- 임의의 data 로 대체 : fillna()

In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.DataFrame({'A': [1, 2, np.nan],
                               'B': [5, np.nan, np.nan],
                               'C': [1, 2, 3]})

In [20]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

### missing value 를 포함하고 있는 모든 row 삭제 - default

In [21]:
df.dropna()

     A    B  C
0  1.0  5.0  1

### missing value 를 포함하고 있는 모든 column 삭제

In [22]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

### missing value 대체

In [23]:
df.fillna(value=0)

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [24]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

### excel file handling

In [25]:
df = pd.read_csv("data/ChatbotData.csv")
df.head()

                 Q            A  label
0           12시 땡!   하루가 또 가네요.      0
1      1지망 학교 떨어졌어    위로해 드립니다.      0
2     3박4일 놀러가고 싶다  여행은 언제나 좋죠.      0
3  3박4일 정도 놀러가고 싶다  여행은 언제나 좋죠.      0
4          PPL 심하네   눈살이 찌푸려지죠.      0